use_frameworks!

platform :ios, '13.0'

##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'ZHHNumberKeyboard_Example' do
  pod 'ZHHNumberKeyboard', :path => '../'

  target 'ZHHNumberKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
